module.exports = {
  ART: "ART",
  MUSIC: "MUSIC",
  VIDEO: "VIDEO",
  UTILITY: "UTILITY",
  COLLECTIBLES: "COLLECTIBLES",
  PHOTOGRAPHY: "PHOTOGRAPHY",
  CINEMATOGRAPHY: "CINEMATOGRAPHY",
  SPORTS: "SPORTS",
};
